chain_split_single_child = true
closure_block_indent_threshold = 1
fn_args_density = "Compressed"
wrap_comments = true
control_brace_style = "ClosingNextLine"
max_width = 80
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true